// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaparaRepositoryPattern.Data.Context;

namespace PaparaRepositoryPattern.Data.Migrations
{
    [DbContext(typeof(PaparaDbContext))]
    [Migration("20221112205715_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PaparaRepositoryPattern.Domain.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TaxNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adress = "Uskudar",
                            City = "Istanbul",
                            CreationDate = new DateTime(2022, 11, 12, 23, 57, 14, 626, DateTimeKind.Local).AddTicks(590),
                            Email = "papara@papara.com",
                            Name = "Papara",
                            Status = 1,
                            TaxNumber = "123"
                        },
                        new
                        {
                            Id = 2,
                            Adress = "Beyoglu",
                            City = "Istanbul",
                            CreationDate = new DateTime(2022, 11, 12, 23, 57, 14, 626, DateTimeKind.Local).AddTicks(2915),
                            Email = "patika@patika.com",
                            Name = "Patika",
                            Status = 1,
                            TaxNumber = "123"
                        },
                        new
                        {
                            Id = 3,
                            Adress = "Beylikduzu",
                            City = "Istanbul",
                            CreationDate = new DateTime(2022, 11, 12, 23, 57, 14, 626, DateTimeKind.Local).AddTicks(2921),
                            Email = "company@company.com",
                            Name = "Company",
                            Status = 1,
                            TaxNumber = "123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
